### ISSUE TITLE
--no_scrub flag causing an error

### ISSUE THREAD

**Issue by Kubitomakita** [10up/wpsnapshots#49]
Error is: `Could not create .wpsnapshots/SNAPSHOT_ID/meta.json.`.

It happens while using the `--no_scrub` while `push`.

Full response:
```Reading configuration from file.
Setup repository: test
Project Slug (letters, numbers, _, and - only): test
Snapshot Description (e.g. Local environment): test
Bootstrapping WordPress...
Testing MySQL connection.
Getting WordPress tables...
Exporting database...
Saving file back up...
Compressing files...
cd '/var/www/html/wp-content'/ && tar  -zcvf /home/wpsnapshots/.wpsnapshots/8ac437c5f8b3bf2f4aa0a79c55ce008e/files.tar.gz .
Compressing database backup...
Could not create .wpsnapshots/SNAPSHOT_ID/meta.json.
(node:12792) UnhandledPromiseRejectionWarning: Error: Command failed: docker-compose exec wpsnapshots /snapshots.sh push --no_scrub -vvv
    at checkExecSyncError (child_process.js:601:13)
    at execSync (child_process.js:641:13)
    at exec_command (C:\www\Internal\underdev-helper\bin\dsnap.js:16:2)
    at snapshot (C:\www\Internal\underdev-helper\bin\dsnap.js:67:19)
    at <anonymous>
(node:12792) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:12792) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by tlovett1** [comment]
This is fixed in 1.5.1. Thanks!
